### ISSUE TITLE
SageMath syllabus

### ISSUE THREAD

**Issue by olexandr-konovalov** [ccp-codima/2020-02-20-lancaster#4]
This is a more long term issue, on which we may work till the start of the workshop.

For the moment in 781141112acf52d09ffceaff7bf8a4ed8107635d I've put draft syllabus  as follows:

- First session with SageMath
- Polynomials and linear algebra
- Elements of programming and 3D graphics
- Matrix Groups
- Orbits and conjugacy classes
- Defensive Programming

This list is partially based on the SageMath Carpentry-style lesson at http://alex-konovalov.github.io/sage-lesson/ on which @ppd22 and I started to work some time ago, although it does not mention some more advanced parts of it. 

We need to think what do we want to teach in Lancaster, and which materials to use. Do we want to revise and try to bring the lesson above up to standard within the remaining two months, or use any other materials that you may have used in the past, revising them and checking how they would match Carpentries pedagogical approaches?

**Comment by hrithik254** [comment]
hi,
i also use sageMath for core electronics engineering subjects, the link you have provided does not exist. I am not sure what remedy you want for the issue. i am not able to understand ur issue

**Comment by olexandr-konovalov** [comment]
The broken link should be https://ccp-codima.github.io/sage-lesson/. We used issues to plan the workshop, which already happened, so there is nothing to address here, thanks.
